# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee8a5234cb08e9786b06b136cb8e2006794cad82aef681b0e4431b59fea68691788433ac51b476fdc6647ec7f507b145686472a1e2eecd239796e85c728f2f2e

test:
  secret_key_base: 91df7854f7259292eb24a2a952d5d1a012bf44b90392b1f11bc66a7d15ea9df36f7d40bc79e3a4a9e91b635291343f32b91c4fae68846b7ea77ac1ca1de4d6fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
